'use strict'
require('dotenv').config()

const CONSTANTS = Object.create(null)
CONSTANTS.MATRIX_HOMESERVER = process.env.MATRIX_HOMESERVER
CONSTANTS.MATRIX_ACCESS_TOKEN = process.env.MATRIX_ACCESS_TOKEN
CONSTANTS.MATRIX_USER_ID = process.env.MATRIX_USER_ID
CONSTANTS.MATRIX_ROOM_ID = process.env.MATRIX_ROOM_ID
CONSTANTS.MATRIX_ROOM_MESSAGE_TYPE = 'm.room.message'
CONSTANTS.MATRIX_NOTICE_TYPE = 'm.notice'
CONSTANTS.MATRIX_STATE_SYNCING = 'SYNCING'
CONSTANTS.MATRIX_STATE_PREPARED = 'PREPARED'

module.exports = CONSTANTS
